baseURL = 'https://overlayfactsheet.com/'
title = 'Overlay Fact Sheet'

# Site language. Available translations in the theme’s `/i18n` directory.
defaultContentLanguage = 'en'

# Renders the default content language in subdir, e.g. /. The root directory / will redirect to /
defaultContentLanguageInSubdir = 'true'

relativeURLs = 'true'

disableKinds = ['taxonomy', 'term']

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ['HTML']

[languages]
  [languages.en]
    contentDir = 'i18n/en'
    weight = 1
    [languages.en.params]
      languageName = 'english'
      languageNameShort = 'en'
      languageCode = 'en'
  [languages.fr]
    contentDir = 'i18n/fr'
    weight = 2
    [languages.fr.params]
      languageName = 'français'
      languageNameShort = 'fr'
      languageCode = 'fr'
  [languages.pt-br]
    contentDir = 'i18n/pt-br'
    weight = 3
    [languages.pt-br.params]
      languageName = 'português brasileiro'
      languageNameShort = 'pt-br'
      languageCode = 'pt-br'
  [languages.ja]
    contentDir = 'i18n/ja'
    weight = 4
    [languages.ja.params]
      languageName = '日本語'
      languageNameShort = 'ja'
      languageCode = 'jp'
  [languages.id]
    contentDir = 'i18n/id'
    weight = 5
    [languages.id.params]
      languageName = 'id'
      languageNameShort = 'id'
      languageCode = 'id'
  [languages.de]
    contentDir = 'i18n/de'
    weight = 5
    [languages.de.params]
      languageName = 'deutsch'
      languageNameShort = 'de'
      languageCode = 'de-de'
  [languages.nl]
    contentDir = 'i18n/nl'
    weight = 6
    [languages.nl.params]
      languageName = 'nederlands'
      languageNameShort = 'nl'
      languageCode = 'nl'

